steps:
  # Construir la imagen del frontend forzando sin caché
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--no-cache",
        "--build-arg",
        "CACHE_BUST=$BUILD_ID",
        "-t",
        "gcr.io/$PROJECT_ID/frontend:latest",
        ".",
      ]

  # Subir la imagen al Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/frontend:latest"]

  # Desplegar en Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud run deploy frontend-service \
          --image gcr.io/$PROJECT_ID/frontend:latest \
          --region us-east1 \
          --platform managed \
          --allow-unauthenticated \
          --port 8080 \
          --set-env-vars NODE_ENV=production,NEXT_PUBLIC_API_URL=https://api.lms.logex.com.ec,APP_KEY=base64:p7tR5ZsljVHi003Ob+gFZsFVJVVws7JxsD5FEwCLioQ=
images:
  - "gcr.io/$PROJECT_ID/frontend:latest"
options:
  logging: CLOUD_LOGGING_ONLY
