import { ElementType } from "react";
import { MdOutlineDashboard } from "react-icons/md";
import {
  GrDocumentText,
  GrDocumentUser,
  GrSubtractCircle,
} from "react-icons/gr";
import { VscRequestChanges } from "react-icons/vsc";
import { CgAddR } from "react-icons/cg";
import { GiPayMoney } from "react-icons/gi";
import { LuUsers } from "react-icons/lu";

type navLink = {
  category: string;
  links: link[];
};

type link = {
  label: string;
  url: string;
  icon: ElementType;
};
export const sidenavLinks: navLink[] = [
  {
    category: "Administración General",
    links: [
      {
        label: "Gestionar usuarios",
        url: "/usuarios",
        icon: LuUsers,
      },
    ],
  },
  {
    category: "Ingresos",
    links: [
      {
        label: "Registrar nuevo",
        url: "/registrar-ingreso",
        icon: CgAddR,
      },
    ],
  },
  {
    category: "Registros",
    links: [
      {
        label: "Descuentos",
        url: "/registros/descuentos",
        icon: GrSubtractCircle,
      },
      {
        label: "Gastos",
        url: "/registros/gastos",
        icon: GiPayMoney,
      },
    ],
  },
  {
    category: "Gestión",
    links: [
      {
        label: "Solicitudes",
        url: "/gestion/solicitudes",
        icon: VscRequestChanges,
      },
      {
        label: "Reportes Personales",
        url: "/gestion/reportes-personales",
        icon: GrDocumentUser,
      },
    ],
  },
  {
    category: "Ingresos especiales",
    links: [
      {
        label: "Inicio",
        url: "/ingresos-especiales",
        icon: MdOutlineDashboard,
      },
    ],
  },
  {
    category: "Presupuesto",
    links: [
      {
        label: "Inicio",
        url: "/presupuesto",
        icon: MdOutlineDashboard,
      },
    ],
  },
  {
    category: "Provisiones",
    links: [
      {
        label: "Inicio",
        url: "/provisiones",
        icon: MdOutlineDashboard,
      },
    ],
  },
];

export const roles = [
  {
    label: "Usuario",
    value: "user",
  },
  {
    label: "Administrador",
    value: "admin",
  },
  {
    label: "Desarrollador",
    value: "developer",
  },
];

export const admnUsers = [
  {
    id: "1710576180",
    name: "AYALA LEON LIDIA MERCEDES",
    email: "lidia.ayala@logex.ec",
    roles: ["user"],
    estado: "activo",
    proyecto: "admn",
    realms: ["user"],
    lastLogin: new Date(2024, 11, 1, 14, 15),
    createdAt: new Date(2024, 0, 7),
  },

  {
    id: "1002366522",
    name: "CARLOSAMA CHACHALO JUAN ROLANDO",
    email: "juan.carlosama@logex.ec",
    roles: ["user"],
    estado: "activo",
    proyecto: "admn",
    realms: ["user"],
    lastLogin: new Date(2024, 11, 1, 14, 15),
    createdAt: new Date(2024, 0, 7),
  },
  {
    id: "1709539546",
    name: "CEVALLOS CASTRO SANTIAGO ROBERTO",
    email: "santiago.cevallos@logex.ec",
    roles: ["user"],
    estado: "activo",
    proyecto: "admn",
    realms: ["user"],
    lastLogin: new Date(2024, 11, 1, 14, 15),
    createdAt: new Date(2024, 0, 7),
  },
  {
    id: "1716568926",
    name: "ESPINOSA CIFUENTES LUIS AURELIO",
    email: "luis.espinosa@logex.ec",
    roles: ["user"],
    estado: "activo",
    proyecto: "admn",
    realms: ["user"],
    lastLogin: new Date(2024, 11, 1, 14, 15),
    createdAt: new Date(2024, 0, 7),
  },
  {
    id: "1723604441",
    name: "HERRERA ROMERO LORENA JACQUELINE",
    email: "lorena.herrera@logex.ec",
    roles: ["user"],
    estado: "activo",
    proyecto: "admn",
    realms: ["user"],
    lastLogin: new Date(2024, 11, 1, 14, 15),
    createdAt: new Date(2024, 0, 7),
  },
  {
    id: "1713243218",
    name: "IZA MORA NICOLAS ALEXANDER",
    email: "nicolas.iza@logex.ec",
    roles: ["user"],
    estado: "activo",
    proyecto: "admn",
    realms: ["user"],
    lastLogin: new Date(2024, 11, 1, 14, 15),
    createdAt: new Date(2024, 0, 7),
  },
  {
    id: "1704680121",
    name: "KENYON ESCOBAR JOHN WALLACE",
    email: "jk@logex.ec",
    roles: ["admin"],
    estado: "activo",
    proyecto: "admn",
    realms: ["user", "root"],
    lastLogin: new Date(2024, 11, 1, 14, 15),
    createdAt: new Date(2024, 0, 7),
  },
  {
    id: "1721362638",
    name: "MERISALDE AGUILAR DIEGO FERNANDO",
    email: "diego.merisalde@logex.ec",
    roles: ["user"],
    estado: "activo",
    proyecto: "admn",
    realms: ["user"],
    lastLogin: new Date(2024, 11, 1, 14, 15),
    createdAt: new Date(2024, 0, 7),
  },
  {
    id: "1721435392",
    name: "MERIZALDE AGUILAR LUIS EDUARDO",
    email: "luis.merisalde@logex.ec",
    roles: ["user"],
    estado: "activo",
    proyecto: "admn",
    realms: ["user"],
    lastLogin: new Date(2024, 11, 1, 14, 15),
    createdAt: new Date(2024, 0, 7),
  },
  {
    id: "1715494926",
    name: "PEREIRA CARRILLO CLAUDIA ISABEL",
    email: "claudia.pereira@logex.ec",
    roles: ["user"],
    estado: "activo",
    proyecto: "admn",
    realms: ["user"],
    lastLogin: new Date(2024, 11, 1, 14, 15),
    createdAt: new Date(2024, 0, 7),
  },
  {
    id: "1751417260",
    name: "QUINTANA GALLARDO ANDREA MICHELLE",
    email: "andrea.quintana@logex.ec",
    roles: ["user"],
    estado: "activo",
    proyecto: "admn",
    realms: ["user"],
    lastLogin: new Date(2024, 11, 1, 14, 15),
    createdAt: new Date(2024, 0, 7),
  },
  {
    id: "1750211698",
    name: "QUINTANA GALLARDO JOSSELYN ANABEL",
    email: "josselyn.quintana@logex.ec",
    roles: ["user"],
    estado: "activo",
    proyecto: "admn",
    realms: ["user"],
    lastLogin: new Date(2024, 11, 1, 14, 15),
    createdAt: new Date(2024, 0, 7),
  },
  {
    id: "1723470306",
    name: "RUBIO MORA OMAR FRANCISCO",
    email: "omar.rubio@logex.ec",
    roles: ["user"],
    estado: "activo",
    proyecto: "admn",
    realms: ["user"],
    lastLogin: new Date(2024, 11, 1, 14, 15),
    createdAt: new Date(2024, 0, 7),
  },
  {
    id: "1003964929",
    name: "TEJADA BALDEON MISHELLE LEONOR",
    email: "mishelle.tejada@logex.ec",
    roles: ["user"],
    estado: "activo",
    proyecto: "admn",
    realms: ["user"],
    lastLogin: new Date(2024, 11, 1, 14, 15),
    createdAt: new Date(2024, 0, 7),
  },
  {
    id: "1721156279",
    name: "ESTRELLA SOLANO DE LA SALA RICARDO JOSE",
    email: "ricardo.estrella@logex.ec",
    roles: ["admin"],
    estado: "activo",
    proyecto: "admn",
    realms: ["user", "root", "developer"],
    lastLogin: new Date(2024, 11, 1, 14, 15),
    createdAt: new Date(2024, 0, 7),
  },
];

export const cnqtUsers = [
  {
    id: "1724028459",
    name: "ALMACHE PROAÑO OSCAR PAUL",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1715033062",
    name: "ALVARADO CONDO RENE PAUL",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1715938104",
    name: "ANGULO CORTEZ RONER ENRIQUE",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1722713904",
    name: "BALAREZO CALDERON PABLO SEBASTIAN",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1724453145",
    name: "BARRE PINARGOTE JAIRO MAURICIO",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1753921954",
    name: "BEDON ESTRELLA JIMMY DANIEL",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1312167222",
    name: "BERMEO LOOR DIMAS FABRICIO",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1722274683",
    name: "BRIONES CHAVEZ SANTO EMILIANO",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1716007024",
    name: "CACHUMBA CACHUMBA CLAUDIO DANILO",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1723626675",
    name: "CAGUA HUILCA MIGUEL ANGEL",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1752436665",
    name: "CAISAGUANO TANDAPILCO DARIO JAVIER",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1720479375",
    name: "CAIZA MURILLO CHRISTOPHER LEONARDO",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1725339764",
    name: "CALDERON GUDIÑO RAFAEL ALEJANDRO",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1003939814",
    name: "CARCELEN MENDEZ JHONNY ALEXANDER",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "0801950569",
    name: "CARCELEN ORTIZ JOSE LUIS",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "0928641794",
    name: "CARDOZO BAZURTO DANILO RICARDO",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "0702910308",
    name: "CARRION GOMEZ JORGE ENRIQUE",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1723539753",
    name: "CARRION OLIVEROS DANNY SAMUEL",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1752872109",
    name: "CHACUA CANCHALA OSCAR ALDAIR",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1721581484",
    name: "CHALUISA MASABANDA BYRON AVELINO",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "0504608829",
    name: "CHAMBA LLASHA MAYCOL JORDAN",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "0504377573",
    name: "CHELA JORGE ERICK SEBASTIAN",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1754416665",
    name: "CHICA RIVERA TANIA GABRIELA",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "2101128813",
    name: "CHICAIZA JIMENEZ ALEX EDUARDO",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1722939640",
    name: "CHICAIZA TIPANGUANO EDGAR GERARDO",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1717359622",
    name: "CHUQUIMARCA MOROCHO DIEGO JAVIER",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1727626028",
    name: "CHUQUIMARCA PUGA JHONNY XAVIER",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1722817333",
    name: "CODENA GALLEGOS ANDRES RODRIGO",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1723519029",
    name: "COLLAGUAZO CHILIGUANO MAURICIO SANTIAGO",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1715528905",
    name: "CORDOVA VELASCO JORGE WLADIMIR",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1001978319",
    name: "CUASPA PIARPUZAN JOSE ALIRIO",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1750487272",
    name: "CUCAS CERON GUSTAVO CRISTIAN",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1756032445",
    name: "CUMBAL GUACALES ALEX DANILO",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1756033526",
    name: "CUMBAL GUACALES ROBINSON JAIRO",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1314131655",
    name: "CUSME CHICHANDA LUIS VICENTE",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1721554630",
    name: "DELGADO SANTACRUZ CARLOS RENAN",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1717188062",
    name: "DIAZ IMBAJA LUIS DARWIN",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1719432963",
    name: "ESCANTA LIQUINCHANA ALEX ARTURO",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1725861981",
    name: "ESPINOZA PISUÑA EDISON",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1720775137",
    name: "ESTRELLA TUTASIG ANDRES EDUARDO",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1715027692",
    name: "FLORES QUITIO KARINA ELIZABETH",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1725182040",
    name: "GALARZA HUILCA CARLOS ARMANDO",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1717379356",
    name: "GALARZA HUILCA HECTOR ALEJANDRINO",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1722964366",
    name: "GALARZA MORETA VICTOR ESTUARDO",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1729269652",
    name: "GALARZA TORRES BRYAN ISRAEL",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1723984843",
    name: "GALARZA TORRES EDISON DANIEL",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1755487830",
    name: "GAROFALO CUCAS RODRIGO DAVID",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1721405528",
    name: "GARZON CALISPA CARLOS DAVID",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1105471807",
    name: "GONZALEZ CALDERON ITALO STALIN",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1750324210",
    name: "GUACALES CUACIALPUD JHON DAVINSON",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1003827068",
    name: "GUALACATA MARTINEZ EDISON DAVID",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1721101713",
    name: "GUAÑUNA NAULAGUARI JAIME ROBERTO",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1754384087",
    name: "GUAPI YUMAGLLA DARWIN IVAN",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1724392988",
    name: "GUDIÑO DELGADO LEONCIO MARCELO",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1755763594",
    name: "GUERRERO RAMIREZ EDISON MIGUEL",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "0706373719",
    name: "GUZMAN GUZMAN NIXON LEONIDAS",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1722178892",
    name: "HERRERA BEJARANO NELSON ANDRES",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1751669761",
    name: "HERRERA CHANCHICOCHA JHONNY OMAR",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1722972567",
    name: "HERRERA ROJAS DIEGO ARMANDO",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1722432992",
    name: "IMBAQUINGO TUGULINAGO CESAR ASCIENCIO",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1719472464",
    name: "INGA PILLAJO EDISON RICARDO",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "0502764020",
    name: "ITURRALDE HERRERA EDISON MARCELO",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1314097633",
    name: "JAMA PINARGOTE MARIANO LEONEL",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "0802695387",
    name: "LARA RAMIREZ MAGNER EDGAR",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "0950197244",
    name: "LLANO VEGA ANTHONY LEONARDO",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1726164732",
    name: "LUNA CASQUETE LUNA CASQUETE LUNA CASQUETE",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "2300212921",
    name: "LUZARRAGA OLVERA JOHAO ALDAIR",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1315861714",
    name: "MARCILLO DELGADO DIXON ALEXANDER",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1713487203",
    name: "MASAQUIZA ENRIQUEZ GALO GUILLERMO",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "0604149880",
    name: "MATUTE GUANGACHI LUCIANO DAVID",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "0924895253",
    name: "MENDEZ BERNAZA DALEMBER ADRIAN",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1724363468",
    name: "MERINO CHAMBA CARLOS ALBERTO",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "0802274571",
    name: "MONTAÑO PEREA JUAN MIGUEL",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1003133723",
    name: "MORA ESPINOSA GUSTAVO JOSE",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "0504856717",
    name: "MOREANO PILATASIG JEFFERSON OSWALDO",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1725049538",
    name: "MOREIRA ZAMBRANO JORDY HENRY",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "0503917668",
    name: "MOROCHO UNAPANTA KELVIN DANIEL",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1722918511",
    name: "MOSCOSO CASTELO PABLO TOMAS",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "2200510200",
    name: "MOSQUERA VERA KEVIN LUIS",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "0803588326",
    name: "NARANJO BRAVO ESTEFANIA ALEXANDRA",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1722368709",
    name: "NUÑEZ YUCAILLA BRYAN HUMBERTO",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1106205550",
    name: "OLAYA GUZMAN JUNIOR ALEXANDER",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1724923386",
    name: "ONOFRE CASTRO MICHAEL VLADIMIR",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1713137667",
    name: "PABON LARA WILLIAM MAURICIO",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1725824740",
    name: "PALADINES CALDERON CARLOS ALBERTO",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1720759735",
    name: "PALLO QUISHPE JOSE ALEJANDRO",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1723904379",
    name: "PASTILLO LANDETA VICTOR HUGO",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "0804384329",
    name: "PEREA CEVALLOS JONATHAN DAVID",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1711495794",
    name: "PEREZ PEREZ JUAN CARLOS",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1719742023",
    name: "PILATAXI VIZCAINO MARCO VINICIO",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "0503797029",
    name: "PINCHA HURTADO EDISON PAUL",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1721877460",
    name: "PINTO RODRIGUEZ NESTOR DAVID",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1755596572",
    name: "PISUÑA PAILLACHO JOSE RODRIGO",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1724873193",
    name: "PISUÑA TOAPANTA DIEGO ANDRES",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1756116818",
    name: "PISUÑA TOAPANTA LUIS GABRIEL",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "0801199407",
    name: "PLAZA TENORIO SIRIO MANUEL",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "0805158847",
    name: "PLUAS ESCOBAR DENYS ALEJANDRO",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "0919295261",
    name: "PLUAS ROSADO EDISON MODESTO",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1723904585",
    name: "PUMBA MARTINEZ PABLO EDUARDO",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1705555457",
    name: "PULIDO CHICAIZA WILMER ELVIS",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1724695155",
    name: "QUIÑONEZ TORO EDISON ALEJANDRO",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1720537664",
    name: "RAGUAJIN MORALES RONALDO ESTEBAN",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1725316713",
    name: "RAMIREZ CORONEL BRIAN EDUARDO",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1715554682",
    name: "RAMOS MONTALUCA CAMILO ANDRES",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1724364723",
    name: "REINA SANDOVAL JESUS LUIS",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1720766989",
    name: "REYES ALVAREZ PAUL",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1723736234",
    name: "ROCHA GUADALUPE JUAN CARLOS",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "0502954068",
    name: "ROJAS ESPINOZA YUMBERTO ERICK",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1752692941",
    name: "ROJAS HURTADO LUIS HERNAN",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1722404471",
    name: "ROMERO HERRERA JORGE FABIÁN",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1721952559",
    name: "RUANO RAMIREZ BRYAN ALEXANDER",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1712971082",
    name: "RUSO RIVERA EDGAR ALEXANDER",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1724309733",
    name: "SAGBIDESPACHO DANIEL EDUARDO",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1724345705",
    name: "SAGBIDESPACHO MARTIN",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1714295393",
    name: "SERRANO ALVAREZ JONNY GABRIEL",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1723437584",
    name: "SILVA VASQUEZ STEVEN NELSON",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1724262293",
    name: "SOLORZANO PEREZ MIGUEL ARTURO",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1723209681",
    name: "SOMOSANCA RAMIREZ EDWIN",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1723118134",
    name: "SOTELO BAQUERA FABIOLA ALEJANDRA",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1723970538",
    name: "SUAREZ CAMPOVERDE KEVIN ANDRES",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1721525407",
    name: "SUAREZ GUALDRON DANIEL ENRIQUE",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1725741414",
    name: "TERRERA SANTA MARTA MAURICIO",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1724068795",
    name: "TUMBACO YUMANA ESTEBAN",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1725355600",
    name: "TUMBACO YUMANA VICTOR MANUEL",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1723879313",
    name: "URCUQUI GUALDRON MICHAEL JAVIER",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1723451607",
    name: "VALENCIA MOSQUERA NELSON RAMON",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1725473007",
    name: "VILLALBA TOAPANTA JORGE LUIS",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
  {
    id: "1712422531",
    name: "ZAMBRANO TORO SANTIAGO ENRIQUE",
    roles: ["user"],
    estado: "activo",
    proyecto: "cnqt",
  },
];

export const cuentas = [
  {
    gastos: {
      proyecto: {
        admn: {
          empresa: {
            prebam: {
              cuenta: [
                "AGUA POTABLE - 5.1.1.02.02",
                "ALIMENTACION - 5.1.1.02.04",
                "CAFETERIA - 5.1.1.02.17",
                "CAPACITACION - 5.1.1.01.09",
                "COMBUSTIBLE DIESEL - 5.1.1.02.10",
                "COMBUSTIBLE GASOLINA SUPER EXTRA - 5.1.1.02.81",
                "COMBUSTIBLE GLP (GAS) - 5.1.1.02.62",
                "COURIER - 5.1.1.02.11",
                "CUSTODIA POLICIAL Y OTROS - 5.1.1.02.12",
                "ENERGIA ELECTRICA - 5.1.1.02.18",
                "ESTIBAJE - 5.1.1.02.19",
                "FALTANTES DE INVENTARIOS (ASUME LOGEX) - 5.1.1.02.20",
                "GASTOS LEGALES - 5.1.1.02.68",
                "GASTOS MEDICOS - 5.1.1.01.18",
                "HOSPEDAJE - 5.1.1.02.28",
                "INGRESOS PREBAM (FALTANTES Y OTROS) - 4.2.1.01.07",
                "MANTENIMIENTO DE BODEGAS COMPRAS - 5.1.1.02.82",
                "MANTENIMIENTO DE BODEGAS SERVICIOS - 5.1.1.02.33",
                "MANTENIMIENTO VEHICULOS - 5.1.1.02.35",
                "MATRICULACION VEHICULOS - 5.1.1.02.36",
                "MOVILIZACION - 5.1.1.02.37",
                "PARQUEO Y GARAGE - 5.1.1.02.45",
                "PEAJES - 5.1.1.02.39",
                "PERSONAL EVENTUAL - 5.1.1.02.41",
                "SEGURIDAD INDUSTRIAL - 5.1.1.02.46",
                "SERVICIO DE INTERNET - 5.1.1.02.50",
                "SERVICIOS PRESTADOS - 5.2.1.02.37",
                "SUELDO EN CONTRA MES ANTERIOR - 2.1.5.01.01",
                "SUMINISTROS DE BODEGA - 5.1.1.02.83",
                "SUMINISTROS DE LIMPIEZA - 5.1.1.02.75",
                "SUMINISTROS DE OFICINA - 5.1.1.02.51",
                "TELEFONIA CELULAR - 5.1.1.02.52",
                "TELEFONIA FIJA - 5.1.1.02.53",
                "TRANSPORTE - 5.2.1.02.28",
                "TRANSPORTE VARIOS (OTROS) - 5.1.1.02.57",
                "VIATICOS ROL  - 5.1.1.02.58",
              ],
            },
            sersupport: {
              cuenta: [
                "ALIMENTACION - 5.1.1.02.04",
                "ANTICIPOS DE QUINCENA A EMPLEADOS - 1.1.20.2.03",
                "BONO DE PRODUCTIVIDAD - 5.1.1.01.19",
                "CAFETERIA - 5.1.1.02.17",
                "CAPACITACION - 5.1.1.01.09",
                "COMBUSTIBLE DIESEL - 5.1.1.02.10",
                "COMBUSTIBLE GASOLINA SUPER EXTRA  - 5.1.1.02.81",
                "COMBUSTIBLE GLP (GAS) - 5.1.1.02.62",
                "COURIER - 5.1.1.02.11",
                "CUENTAS POR COBRAR VARIOS DESCUENTOS EMPLEADOS - 1.1.20.4.11",
                "CUSTODIA POLICIAL REEMBOLSO CN - 5.1.1.02.87",
                "CUSTODIA POLICIAL Y OTROS - 5.1.1.02.12",
                "ENERGIA ELECTRICA - 5.1.1.02.18",
                "ESTIBAJE - 5.1.1.02.19",
                "FALTANTES DE INVENTARIOS (ASUME LOGEX) - 5.1.1.02.20",
                "FALTANTES POR COBRAR EMPLEADOS Y TRANSPORTISTAS - 5.1.1.02.22",
                "GASTO TRANSPORTE MATERIALES FEP - 5.1.1.02.79",
                "GASTOS BANCARIOS - 5.1.1.02.23",
                "GASTOS LEGALES - 5.1.1.02.68",
                "GASTOS MEDICOS - 5.1.1.02.25",
                "GASTOS POR DESCUENTOS - 5.1.1.02.86",
                "HOSPEDAJE - 5.1.1.02.28",
                "INGRESOS CRUCE FTE - 4.2.1.01.12",
                "MANTENIMIENTO DE BODEGAS COMPRAS  - 5.1.1.02.82",
                "MANTENIMIENTO DE BODEGAS SERVICIOS - 5.1.1.02.33",
                "MANTENIMIENTO MONTACARGAS - 5.1.1.02.70",
                "MANTENIMIENTO VEHICULOS - 5.1.1.02.35",
                "MATRICULACION VEHICULOS - 5.1.1.02.36",
                "MOVILIZACION - 5.1.1.02.37",
                "MULTAS A EMPLEADOS - 2.1.5.01.08",
                "MULTAS DE TRANSITO  - 1.1.2.02.01",
                "PARQUEO Y GARAGE - 5.1.1.02.45",
                "PEAJES - 5.1.1.02.39",
                "PERSONAL EVENTUAL - 5.1.1.02.41",
                "PRESTAMOS QUIROGRAFARIOS - 2.1.5.01.06",
                "PRESTAMOS Y ANTICIPOS EMPLEADOS - 1.1.20.2.01",
                "RECUPERACION VALORES COMISION DE REPARTO - 4.2.1.01.10",
                "RESTRICCION VEHICULAR - 5.1.1.02.84",
                "RETENCION JUDICIAL - 2.1.5.01.12",
                "SEGURIDAD INDUSTRIAL - 5.1.1.02.46",
                "SERVICIO DE INTERNET - 5.1.1.02.50",
                "SUBSIDIO IESS - 5.1.1.01.01",
                "SUELDO EN CONTRA MES ANTERIOR - 2.1.5.01.01",
                "SUELDOS Y SALARIOS - 5.1.1.01.01",
                "SUMINISTROS DE BODEGA - 5.1.1.02.83",
                "SUMINISTROS DE LIMPIEZA - 5.1.1.02.75",
                "SUMINISTROS DE OFICINA - 5.1.1.02.51",
                "TELEFONIA CELULAR - 5.1.1.02.52",
                "TELEFONIA FIJA - 5.1.1.02.53",
                "TRANSPORTE VARIOS (OTROS) - 5.1.1.02.57",
                "UNIFORMES OPERATIVO - 5.1.1.02.76",
                "ventas logex.com.ec - 2.1.7.01.05",
                "VIATICOS PROVEEDORES - 5.1.1.02.85",
                "VIATICOS ROL  - 5.1.1.02.58",
              ],
            },
          },
          responsable: admnUsers,
        },
        cnqt: {
          responsable: cnqtUsers,
        },
      },
    },
  },
];

// Descuentos Masivos
export const areas = [
  {
    label: "Admin",
    value: "admin",
  },
  {
    label: "Bodega",
    value: "bodega",
  },
  {
    label: "Grifería",
    value: "griferia",
  },
  {
    label: "Monitoreo",
    value: "monitoreo",
  },
  {
    label: "Porteo",
    value: "porteo",
  },
  {
    label: "Proveedor",
    value: "proveedor",
  },
  {
    label: "Sanitarios",
    value: "sanitarios",
  },
  {
    label: "Temporal",
    value: "temporal",
  },
  {
    label: "Transporte",
    value: "transporte",
  },
];

export const proyectos = [
  {
    label: "ADMN",
    value: "admn",
  },
  {
    label: "CNQT",
    value: "cnqt",
  },
];

export const cuentasMasivas = [
  {
    label: "RECUPERACION VALORES COMISION DE REPARTO - 4.2.1.01.10",
    value: "4.2.1.01.10",
  },
  {
    label: "FALTANTES POR COBRAR EMPLEADOS Y TRANSPORTISTAS - 5.1.1.02.22",
    value: "5.1.1.02.22",
  },
];
